Rename IndentFirstArgument cop
This was changed in Rubocop v0.68

Fixes and error on the current Rubocop version v0.74:

    Error: The `Layout/FirstParameterIndentation` cop has been renamed
    to `Layout/IndentFirstArgument`. (obsolete configuration found in
    ~/.gem/ruby/1.6.2/gems/radius-spec-0.2.1/common_rubocop.yml, please
    update it)