Release version 0.5.0
[Full Changelog](https://github.com/RadiusNetworks/radius-spec/compare/v0.4.0...v0.5.0)

Enhancements
------------

- Add common VCR configuration (Aaron Kromer, #16)
  - Filters out `Authorization` headers
  - Filters out the following sensitive/environment varying `ENV` values, as
    well as their URL and form encoded variants:
    - `AWS_ACCESS_KEY_ID`
    - `AWS_SECRET_ACCESS_KEY`
    - `GOOGLE_CLIENT_ID`
    - `GOOGLE_CLIENT_SECRET`
    - `RADIUS_OAUTH_PROVIDER_APP_ID`
    - `RADIUS_OAUTH_PROVIDER_APP_SECRET`
    - `RADIUS_OAUTH_PROVIDER_URL`
- Add "temp file" helpers for working with file stubs (Aaron Kromer, #15)
- Upgrade to Rubocop 0.59.x (Aaron Kromer, #14)
- Adjust common Rubocop configuration (Aaron Kromer, #14)
  - `Layout/EmptyLineAfterGuardClause` is enabled by default
  - Enable `Rails/SaveBang` to highlight potential lurking issues
  - Expand `Rails/FindBy` and `Rails/FindEach` to check all `/app` and `/lib`
  - Add more functional methods
    - `default_scope`
    - `filter_sensitive_data`
- Add `build!` factory method to compliment `build` to help resolving Rubocop
  violations for `Rails/SaveBang` (Aaron Kromer, #14)
- Load model factory for specs tagged with 'type: :mailer' (Aaron Kromer, #11)
- Include the following negated RSpec matchers (Aaron Kromer, #12)
  - `exclude` / `excluding`
  - `not_eq`
  - `not_change`
  - `not_raise_error` / `not_raise_exception`

Bug Fixes
---------

- Fix `NoMethodError: undefined method 'strip'` when the fixture path is a
  `Pathname` object (Aaron Kromer, #13)